<a href="https://colab.research.google.com/github/HenriqueHideaki/BibliotecasPython/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arrays
## [Numpy Documentantion Link](https://numpy.org/doc/1.23/user/basics.creation.html)

In [ ]:
import numpy as np

# np.array()

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11]])
print(a)

[list([1, 2, 3, 4, 5, 6]) list([7, 8, 9, 10, 11])]


<ipython-input-11-32d8b3fd2abe>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1,2,3,4,5,6],[7,8,9,10,11]])


#np.zeros()

In [ ]:
zero_array = np.zeros(shape = (5,3,6))
zero_array  

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

#np.ones()

In [ ]:
um_array = np.ones((3,2))
um_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#np.empty()

In [ ]:
vazio = np.empty((3,4))
print(vazio)

[[1.78294300e-316 2.22809558e-312 6.79038654e-313 6.79038653e-313]
 [2.37663529e-312 2.14321575e-312 2.37663529e-312 2.56761491e-312]
 [1.08221785e-312 7.93287846e+165 1.64182472e-306 0.00000000e+000]]


#np.arange()

In [ ]:
arr = np.arange(10,100,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

#np.linspace()

In [ ]:
array_linear = np.linspace(1,100,30,endpoint = False)
array_linear

array([ 1. ,  4.3,  7.6, 10.9, 14.2, 17.5, 20.8, 24.1, 27.4, 30.7, 34. ,
       37.3, 40.6, 43.9, 47.2, 50.5, 53.8, 57.1, 60.4, 63.7, 67. , 70.3,
       73.6, 76.9, 80.2, 83.5, 86.8, 90.1, 93.4, 96.7])

In [ ]:
print(zero_array.shape)# formato do array, quantidade em cada dimensão
print(zero_array.size)# quantidade de elementos - tamanho
print(zero_array.ndim)# dimensao

(5, 3, 6)
90
3


#Transformando vetor 2D em vetor 3D

In [ ]:
a = np.array([1,2,3])
print(a.ndim)

1


In [ ]:
a2 = a[np.newaxis,:]
print(a2.ndim)
print(a2.shape)
print(a2)

2
(1, 3)
[[1 2 3]]


In [ ]:
a3 = a[:,np.newaxis]
print(a3.ndim)
print(a3.shape)
print(a3)

2
(3, 1)
[[1]
 [2]
 [3]]


In [ ]:
print(a3[0])


1


#Concatenando Array

In [ ]:
from numpy.matrixlib.defmatrix import concatenate
a = np.array([1,2,3])
b = np.array([4,5,6])

c = concatenate((a,b))
d = concatenate((b,a))
print(c)
print(d)

[1 2 3 4 5 6]
[4 5 6 1 2 3]


#Consultado itens em um array 


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
maior_8 = a[a>8]
par = a[a%2==0]
print(a)
print("-"*20)
print(maior_8)
print("-"*20)
print(par)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
[ 9 10 11 12]
--------------------
[ 2  4  6  8 10 12]


#operações com arrays

In [ ]:
a = np.array([1,2,3])
print(a.sum())
print(a.max())
print(a.mean())

6
3
2.0


#Gerando amostras aleatórias

In [ ]:
from numpy.random import default_rng

rng = default_rng()
aleatorio = rng.integers(10, size= (2,4))
print(aleatorio)

[[7 1 1 2]
 [2 9 3 9]]
